Change program to ignore invalid install locs
Instead of validating all install locations before copying any files
over, now just ignores invalid install locations and tries to keep
copying.

This greatly simplifies the program as it's no longer necessary to keep
a variable tracking all install locations.

diff --git a/bupdate b/bupdate
--- a/bupdate
+++ b/bupdate
@@ -4,21 +4,7 @@ config="installdirs" # PATH TO INSTALL FILES LIST.
 meleename="WillsetMelee"
 stdname="WillsetS"
 
-[ "$(id -u)" != "0" ] && echo "Please run as superuser or files cannot be copied!" && exit 1
-
-# Get install dirs from config file.
-installs=""
-while read -r line; do
-  installs="$installs$line "
-done < <(grep -vE '^#|$#' $config)
-echo $installs
-
-for install in $installs
-do
-  [ ! -d $install ] && echo "Freeciv data directory not present at $install. Is freeciv installed?" && exit 1
-done
-
-# Validation
+# Validate that copy targets are present.
 
 # $1: directory
 # $2: serv file
@@ -39,13 +25,18 @@ stddir="$stdname/WillsetS"
 stdserv="$stdname/WillsetS.serv"
 validate $stddir $stdserv $stdname
 
-# Copy
-for install in $installs
-do
-  echo "Placing installs in $install"
-  cp -r "$meleedir" "$install"
-  cp -r "$meleeserv" "$install"
-  cp -r "$stddir" "$install"
-  cp -r "$stdserv" "$install"
-done
+[ "$(id -u)" != "0" ] && echo "Please run as superuser or files cannot be copied!" && exit 1
 
+# Copies to all present install directories.
+# In order to simplify program logic, just ignores not-present directories.
+while read -r line; do
+  if [ -d $line ]; then  
+    echo "Placing installs in $install"
+    cp -r "$meleedir" "$install"
+    cp -r "$meleeserv" "$install"
+    cp -r "$stddir" "$install"
+    cp -r "$stdserv" "$install"
+  else
+    echo "Install directory $line not present; not copying here."
+  fi
+done < <(grep -vE '^#|$#' $config)
